# Generated by Django 4.2.7 on 2023-12-09 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_finish', models.DateTimeField(null=True, verbose_name='Дата завершения')),
                ('price', models.FloatField(verbose_name='Стоимость заказа')),
                ('address_delivery', models.CharField(max_length=150, verbose_name='Адресс доставки')),
                ('status', models.CharField(choices=[(1, 'Создан'), (2, 'Отменен'), (3, 'В пути'), (4, 'Завершен')], max_length=150, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['date_create'],
            },
        ),
        migrations.CreateModel(
            name='Suplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название потсавщика')),
                ('agent_name', models.CharField(max_length=100, verbose_name='Иммя агента')),
                ('agent_firstname', models.CharField(max_length=100, verbose_name='Фамилия поставщика')),
                ('agent_patronymic', models.CharField(max_length=100, verbose_name='Отчество агента')),
                ('exist', models.BooleanField(default=True, verbose_name='Сотрудничаем?')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Chegue',
            fields=[
                ('date_print', models.DateTimeField(auto_now_add=True, verbose_name='Дата выдачи')),
                ('address_print', models.CharField(max_length=150, verbose_name='Адресс выдачи')),
                ('terminal', models.CharField(max_length=100, verbose_name='Номер терминала')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='place.order')),
            ],
            options={
                'verbose_name': 'Чек',
                'verbose_name_plural': 'Чеки',
                'ordering': ['terminal', 'date_print'],
            },
        ),
        migrations.CreateModel(
            name='Things',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='<none>', max_length=120, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.FloatField(default=0, verbose_name='Стоимость')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_update', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменеия')),
                ('date_expired', models.DateField(null=True, verbose_name='Дата истечения срока')),
                ('photo', models.ImageField(null=True, upload_to='image/%Y/%m/%d', verbose_name='Фото')),
                ('exist', models.BooleanField(default=True, verbose_name='В наличии?')),
                ('suplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='place.suplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Хрень',
                'verbose_name_plural': 'Хреновины',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Pos_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('price', models.FloatField(verbose_name='Сумма')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='place.order', verbose_name='Заказ')),
                ('thing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='place.things', verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Позиция',
                'verbose_name_plural': 'Позиции',
                'ordering': ['thing', 'order', 'price'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='thing',
            field=models.ManyToManyField(through='place.Pos_order', to='place.things'),
        ),
    ]
