# Generated by Django 4.2.7 on 2023-12-09 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chegue',
        ),
    ]
