# Generated by Django 4.2.7 on 2023-12-09 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_chegue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chegue',
        ),
    ]
