# Generated by Django 4.2.7 on 2023-12-09 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0004_delete_chegue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chegue',
            fields=[
                ('date_print', models.DateTimeField(auto_now_add=True, verbose_name='Дата выдачи')),
                ('address_print', models.CharField(max_length=150, verbose_name='Адресс выдачи')),
                ('terminal', models.CharField(max_length=100, verbose_name='Номер терминала')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='place.order')),
            ],
            options={
                'verbose_name': 'Чек',
                'verbose_name_plural': 'Чеки',
                'ordering': ['terminal', 'date_print'],
            },
        ),
    ]
