# Generated by Django 4.2.7 on 2023-12-13 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0007_order_chegue_pos_order_order_thing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'Создан'), ('2', 'Отменен'), ('3', 'В пути'), ('4', 'Завершен')], max_length=150, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='things',
            name='suplier',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='place.suplier', verbose_name='Поставщик'),
            preserve_default=False,
        ),
    ]
