# Generated by Django 4.2.7 on 2023-12-13 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0008_alter_order_status_alter_things_suplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='things',
            name='suplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='place.suplier', verbose_name='Поставщик'),
        ),
    ]
